---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb 
  namespace: ${NAMESPACE} 
  labels:
    app: mariadb 
spec:
  containers:
  - name: mariadb
    image: mariadb/server
    resources:
      limits:
        cpu: 10m
        memory: 100Mi
      requests:
        cpu: 8m
        memory: 90Mi
    env:
      - name: MARIADB_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysecret 
            key: password 
    ports:
        - containerPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-service
  namespace: ${NAMESPACE} 
spec:
  type: LoadBalancer 
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb
