apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx 
automountServiceAccountToken: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: Recreate
  replicas: 1 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: nginx 
      containers:
      - name: nginx
        image: bdereims/acme-nginx:latest 
        env:
          - name: MARIADB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
        ports:
        - containerPort: 80
