AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVDVENDQXZHZ0F3SUJBZ0lVV1pwUERTUHp2UHh5T0RESzJhejFUYlp0aXlrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dhUXhDekFKQmdOVkJBWVRBa1pTTVEwd0N3WURWUVFJREFSalVHOWtNUTB3Q3dZRFZRUUhEQVJqVUc5awpNUTB3Q3dZRFZRUUtEQVJqVUc5a01RMHdDd1lEVlFRTERBUmpVRzlrTVNzd0tRWURWUVFERENKamIyNTBjbTlzCmJHVnlMbUY2TFhadFl5NWpiRzkxWkMxbllYSmhaMlV1Ym1WME1Td3dLZ1lKS29aSWh2Y05BUWtCRmgxaFpHMXAKYmtCaGVpMTJiV011WTJ4dmRXUXRaMkZ5WVdkbExtNWxkREFlRncweU1UQTNNREV4TlRReU16aGFGdzB5TWpBMwpNREV4TlRReU16aGFNSUdrTVFzd0NRWURWUVFHRXdKR1VqRU5NQXNHQTFVRUNBd0VZMUJ2WkRFTk1Bc0dBMVVFCkJ3d0VZMUJ2WkRFTk1Bc0dBMVVFQ2d3RVkxQnZaREVOTUFzR0ExVUVDd3dFWTFCdlpERXJNQ2tHQTFVRUF3d2kKWTI5dWRISnZiR3hsY2k1aGVpMTJiV011WTJ4dmRXUXRaMkZ5WVdkbExtNWxkREVzTUNvR0NTcUdTSWIzRFFFSgpBUllkWVdSdGFXNUFZWG90ZG0xakxtTnNiM1ZrTFdkaGNtRm5aUzV1WlhRd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDZDA1bWl0c1ZZd09pZUVsN21rcGx0OVVxTSt6NG9GU3h4Nm9oVjN4R08KVHAxRWErNUlxa0pkT2lCRFBvSnZlQ0k0dVo4ZG1HaWpWN1B6ZHZoWjBRM0NmNTNJamNWbGU5ZUJuK1BPYVNucApLSHVWUFRJRnVUUjdvT3dvNDNRYzkyRUFCVTRqTmpmZkRkcVBTaWV0SVVzdy9yTXJVNW1oNWxJSS9ENy9yZ215CnBmRjVESnFodUx1WmpabCtRcDg2UVViOGczU3JCQzh1SjhWTEY4TDV6N0Y0TVNwbzQvb0wxNUZKTk9RWG1QMTkKVFA3eDdPMDAzdWp1T1ZiQmNCbks4Ym1UL2czd1JnWGE1NUhzVSt3d0xvSlFDL3hoeUtSY2FEcTJRTldpOCt5OQpDczFoNnFzYnlaWUN4cHZWM1ZlRFk3TVd3TWZXRm9JdWdZOEVQSmFBODVodEFnTUJBQUdqTVRBdk1DMEdBMVVkCkVRUW1NQ1NDSW1OdmJuUnliMnhzWlhJdVlYb3RkbTFqTG1Oc2IzVmtMV2RoY21GblpTNXVaWFF3RFFZSktvWkkKaHZjTkFRRUxCUUFEZ2dFQkFKdXFjS0VCTHFzWjFVQ0E2TUdMcG9MTGNVay9pRmU1OEgxWjl2eE55LzFrQUpNVgp6VDdwZzd6ODliY2sydVpxbElFaW10ZTVZSGRRaUYvM3pyRE9ITHdkYnpHOURoRnhBbVc3L2xvWTQ2eVNOSXNVCkpEUTJMV3Y0endSOTV3QmkrTElJbkJ1dTdSU1M4ZGl0cnhTSGJWV0E4NkZWcThKbXdFZW9UM3NMNjJSVDdSQ3QKVEtHclhRNlZCN2h2Y0JBKzdiZWltS0lkOXNTaVdPK3ZWNXZpd1R2V0FPZ1VWUHJTdERLU2xGS1BNbXczWjIvZQpqNE5yaGdVVTdYaDdTeGxOdkFqUHQwTzRnRmtZUldQRWpUUHRTZjlTK0tlME9MZHBLMm9kZXljQXhBa05adXpKClgzY1JUaEJ4WDdZWkh5ZGozNXZJRWlhTFdZVUtycGZ3SWxjQVBscz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROLLER: controller.az-vmc.cloud-garage.net
AVI_DATA_NETWORK: sddc-cgw-network-1
AVI_DATA_NETWORK_CIDR: 192.168.1.0/24
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_PASSWORD: <encoded:Vk13YXJlMSE=>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tkgm
CLUSTER_PLAN: dev
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "false"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: 192.168.1.5
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /SDDC-Datacenter
VSPHERE_DATASTORE: /SDDC-Datacenter/datastore/WorkloadDatastore
VSPHERE_FOLDER: /SDDC-Datacenter/vm/TKG
VSPHERE_NETWORK: sddc-cgw-network-1
VSPHERE_PASSWORD: <encoded:QSpmVU9aVHlCaTdpbS01>
VSPHERE_RESOURCE_POOL: /SDDC-Datacenter/host/Cluster-1/Resources/Compute-ResourcePool
VSPHERE_SERVER: vcenter.sddc-34-202-46-89.vmwarevmc.com
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCgLZqzi7XWGu4znxv/xXhD1GlRMcap4nZYyuN/+PRx8VeG7TzIMiCee+3b25aY4hxhZydnDBKu1VzZg24QAAGaQgGi3km7lwhkQCtFM+IZB0txeGCfGKpCg+00rtrEbZsS5yFPBkHTwaVDHFU2ttmHVlzlOiseyCyeSj3szcUrtVOtv+nvORwORwjXvuc8bEsRDwrRYzANesPScjlczgWhfuNZOyvKePcUDrxmdybaGys9LWavmNq4ycA/yLGx67kdTaan0g30l7XK374n++AHFTIjRMA+Uxg6gQj6X1SVhWjC/BZNioxjX8gPr5aBaZ4MO9lxuTJHrp2cvSuaZWAt grease-monkey@grease-monkey
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: cloudadmin@vmc.local
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
