VSPHERE_CONTROL_PLANE_ENDPOINT: "prod.cpod-devready.az-fkd.cloud-garage.net"
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "3"
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "12288"
VSPHERE_WORKER_NUM_CPUS: "4"
WORKER_MACHINE_COUNT: 3 

CLUSTER_PLAN: prod

VSPHERE_INSECURE: true
VSPHERE_DATACENTER: /dc01
VSPHERE_DATASTORE: /dc01/datastore/cl01-ds-vsan01
VSPHERE_STORAGE_POLICY_ID: "vSAN Default Storage Policy"
VSPHERE_FOLDER: /dc01/vm/TKG
VSPHERE_NETWORK: /dc01/network/Management Networks/workload
VSPHERE_PASSWORD: <encoded:TUNNb3U2cU9Ob3Yh>
VSPHERE_RESOURCE_POOL: /dc01/host/cl01/Resources/Tanzu
VSPHERE_SERVER: vcsa.cpod-devready.az-fkd.cloud-garage.net
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDMi4ogDhbVLr6lWfZaUNMpXaMd/r2j/m915jGnkttzEb+TAUyoWkJnU8ldQXkFWOxo5lL3ezmz00BvxHhZMg1swVPefXe7Hbpr+eBGVM/cSHi2Ca0mSsFNx/mM1zyicxLWJVcm47gr+QvOrROH4VXMjNm+oQoigH20j7Juwpt4CZBahuzvoTvb/mcx30OIvKfsI8eEnEb3GBAm6IldlUQKUdSbQKxRvRQXm47+P+LG+XSkrubXKWzlSy59GTUpiByTdaBOkGXHRvWJzLSodG+ZaDO/74pRkVL4+sprjXInyNY1YzT8eUD3D6FQYRKkx4w+uYfJVP4ctX50HPixO5Ll sixty9@sixty9
VSPHERE_TLS_THUMBPRINT: B0:02:50:29:A5:40:BE:5C:55:7C:55:56:67:F0:54:36:DB:2F:5B:56
VSPHERE_USERNAME: administrator@vsphere.local

ENABLE_MHC: true 
ENABLE_MHC_CONTROL_PLANE: true
ENABLE_MHC_WORKER_NODE: true
MHC_UNKNOWN_STATUS_TIMEOUT: 5m
MHC_FALSE_STATUS_TIMEOUT: 12m

AVI_DISABLE_INGRESS_CLASS: false 

ENABLE_DEFAULT_STORAGE_CLASS: true

ANTREA_TRACEFLOW: true 

ENABLE_AUTOSCALER: false 
AUTOSCALER_MAX_NODES_TOTAL: "20"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_ADD: "10m"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_DELETE: "10s"
AUTOSCALER_SCALE_DOWN_DELAY_AFTER_FAILURE: "3m"
AUTOSCALER_SCALE_DOWN_UNNEEDED_TIME: "10m"
AUTOSCALER_MAX_NODE_PROVISION_TIME: "15m"
AUTOSCALER_MIN_SIZE_0: "3"
AUTOSCALER_MAX_SIZE_0: "10"
AUTOSCALER_MIN_SIZE_1: "3"
AUTOSCALER_MAX_SIZE_1: "10"
AUTOSCALER_MIN_SIZE_2: "3"
AUTOSCALER_MAX_SIZE_2: "10"
