apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: acme  
  namespace: tkgs 
spec:
 topology:
   controlPlane:
     count: 3 
     class: best-effort-small
     storageClass: vsan-default-storage-policy 
   workers:
     count: 4
     class: best-effort-small
     storageClass: vsan-default-storage-policy
 distribution:
   version: v1.19
 settings:
   network:
     cni:
       name: antrea  #But could be left blank if using the default
     services:
       cidrBlocks: ["10.99.0.0/16"]
     pods:
       cidrBlocks: ["10.98.0.0/16"]
   storage:
     defaultClass: vsan-default-storage-policy
