apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: dev-cluster
  namespace: tkg-service 
spec:
 topology:
   controlPlane:
     count: 1 
     class: best-effort-xsmall
     storageClass: tanzu 
   workers:
     count: 3
     class: best-effort-xsmall
     storageClass: tanzu 
 distribution:
   version: v1.18.5
 settings:
    network:
      cni:
        name: antrea  #But could be left blank if using the default
      services:
        cidrBlocks: ["10.99.0.0/16"]
      pods:
        cidrBlocks: ["10.98.0.0/16"]
