VSPHERE_INSECURE: true
AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVRRENDQXlpZ0F3SUJBZ0lVWHRkc2xZbWdsbURrbENSOUdlWUVUL0p2YjZnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dib3hDekFKQmdOVkJBWVRBa1pTTVEwd0N3WURWUVFJREFSalVHOWtNUTB3Q3dZRFZRUUhEQVJqVUc5awpNUTB3Q3dZRFZRUUtEQVJqVUc5a01RMHdDd1lEVlFRTERBUmpVRzlrTVRZd05BWURWUVFEREMxamIyNTBjbTlzCmJHVnlMbU53YjJRdFlXZDBlblV1WVhvdFptdGtMbU5zYjNWa0xXZGhjbUZuWlM1dVpYUXhOekExQmdrcWhraUcKOXcwQkNRRVdLR0ZrYldsdVFHTndiMlF0WVdkMGVuVXVZWG90Wm10a0xtTnNiM1ZrTFdkaGNtRm5aUzV1WlhRdwpIaGNOTWpFd05qRXlNRFkwTXpJMldoY05Nakl3TmpFeU1EWTBNekkyV2pDQnVqRUxNQWtHQTFVRUJoTUNSbEl4CkRUQUxCZ05WQkFnTUJHTlFiMlF4RFRBTEJnTlZCQWNNQkdOUWIyUXhEVEFMQmdOVkJBb01CR05RYjJReERUQUwKQmdOVkJBc01CR05RYjJReE5qQTBCZ05WQkFNTUxXTnZiblJ5YjJ4c1pYSXVZM0J2WkMxaFozUjZkUzVoZWkxbQphMlF1WTJ4dmRXUXRaMkZ5WVdkbExtNWxkREUzTURVR0NTcUdTSWIzRFFFSkFSWW9ZV1J0YVc1QVkzQnZaQzFoClozUjZkUzVoZWkxbWEyUXVZMnh2ZFdRdFoyRnlZV2RsTG01bGREQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOVHQwbHRpMlFvTmJiOGRNcWNmaW10TFowQThyWjVEWGxvVldnRFNaQ2FtdngzMApPOStGTDRhcTJ5RjR5eHIxVjBoTDlGTUZzN2lobFhrcU91bDRVV1p6MHNMVTdhM1NBQ3hCNTZQMW9ZYTBINUVGCkN0b1ZJTzlxRFRqa1A1dCtYL3I1NmRzdGh3T0xHMTd2MHI5L0VFOTM5enR0MG5HVXd3UDFjbW9CU1JicC9OTzMKRzdPMERNSHZWV2lZWUtLZUI4ZVA4bGdxc2d2OGRaQzA4azJRazZSMGVNQVJSM3NtOHpoZVFlVG92N1VJSlpyZgpDN3g2ZVp0MmxibnBUSXVNNmpaVkVkMks0aTJyNng3SzY5QXpkMStRUmdvdFpqQTBmUThsS2xET3VBQTBoRzJvCndnWll4dzZEdElrWFM2eEVjejdLM3pXaFNLVTVuUjAvWTRGZWJUY0NBd0VBQWFNOE1Eb3dPQVlEVlIwUkJERXcKTDRJdFkyOXVkSEp2Ykd4bGNpNWpjRzlrTFdGbmRIcDFMbUY2TFdaclpDNWpiRzkxWkMxbllYSmhaMlV1Ym1WMApNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUN5NzRUSElHSzF3T2pTNndXYzdtQUo3cnNlcGxlVy9RSFp1eTdDCitYejZRMjNpbjlQMnRYaGNWMWl1elhrekE3VHQwN0NtcGlQbmxOcTcxelovWUt6VXRuZTFrUnI1Y1p3dDZDOVMKSW1nUlAvZTFiUHhacmhKZlRjNW9OZm5ISWpteDJ2SDYrck9hWmxxamJobGpqSXJDVzdqelpLd3lsRUpWbTZJUApPa2srRXRSNzVjZWdvWHpKV1AzL3oxODBsYUFaQ28vZ1JxcnVqMEhxczlTYWVtcUhYOEwvUVNPQVoyanJrZkFICmVIeWN5R2pkdGFUKy9Xb001YU9lT2R5RWVHOEJwcDZYV2lKMzR1MmtoM2hkMEwrWkZvVFVpcWZUV2ptSlVVRloKMWRNRklyR2N1V24wNS9WdFJIbm0vV21INTZXRzRoYmR5WmJRZ25xNVNKbkpmK1R6Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROLLER: controller.cpod-agtzu.az-fkd.cloud-garage.net
AVI_DATA_NETWORK: Frontend
AVI_DATA_NETWORK_CIDR: 10.30.3.0/24
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_PASSWORD: <encoded:SDN2TVgxYXNxMU0h>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tkgm
CLUSTER_PLAN: dev
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: oidc 
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: 0oayeze6oNFtYPLyN5d6
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: cs1eh6gklgZfL9ayyV1EDCHYU_GKLBwIJffqmH6g
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: groups
OIDC_IDENTITY_PROVIDER_ISSUER_URL: https://dev-48789569.okta.com
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: "email"
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: email
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY_ENABLED: "true"
TKG_HTTP_PROXY: http://172.17.20.1:3128
TKG_HTTPS_PROXY: http://172.17.20.1:3128
TKG_NO_PROXY: 192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,*.cpod-agtzu.az-fkd.cloud-garage.net
VSPHERE_CONTROL_PLANE_DISK_GIB: "40"
VSPHERE_CONTROL_PLANE_ENDPOINT: 172.17.20.121
VSPHERE_CONTROL_PLANE_MEM_MIB: "8192"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /cPod-AGTZU
VSPHERE_DATASTORE: /cPod-AGTZU/datastore/vsanDatastore
VSPHERE_FOLDER: /cPod-AGTZU/vm/TKG
VSPHERE_NETWORK: Management
VSPHERE_PASSWORD: <encoded:SDN2TVgxYXNxMU0h>
VSPHERE_RESOURCE_POOL: /cPod-AGTZU/host/Cluster/Resources/TKGm
VSPHERE_SERVER: vcsa.cpod-agtzu.az-fkd.cloud-garage.net
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmsBF8HGkl+gr0KlH6jJGaSLpVbaY8Yrm7nkmj9hR/EM2m6eYYHqg8LNTmQT2DR35dr0PXHiyWaT4BC9qA3qCJYrCpGE4eO9fhB5gYhOpaZ/5YgZNKarhGR7LQva+LRInJPH7KWR/TvQE0dOaQ+QsIWoEEZvAgeOsroFN5JlMtVZCr/VmpRL5kOHI0cdmycYXTgChWCCEqmjVsc+Z+vZSjSl96m5uk1qGOUX/1YdRuVNhR8o2SptO0EHUD0Wns3c3mpqqPtFOrWcFbWJ8CQRktaQfsXzb6Racc+FC1vexfXFaU9yCXMyfs+fzeknrnHiGpW3Dn9sIct1eT4Swva42D grease-monkey@grease-monkey
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@cpod-agtzu.az-fkd.cloud-garage.net
VSPHERE_WORKER_DISK_GIB: "40"
VSPHERE_WORKER_MEM_MIB: "8192"
VSPHERE_WORKER_NUM_CPUS: "2"
