VSPHERE_INSECURE: true
AVI_CA_DATA_B64: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURzakNDQXBxZ0F3SUJBZ0lVTEwvRC9sZ0ZGMkowd0Y4cUVmdzRkdW1MRUdNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERU5NQXNHQTFVRUNBd0VZMUJ2WkRFTk1Bc0dBMVVFQnd3RVkxQnZaREVOTUFzR0ExVUVDZ3dFWTFCdgpaREVOTUFzR0ExVUVDd3dFWTFCdlpERTJNRFFHQTFVRUF3d3RZMjl1ZEhKdmJHeGxjaTVqY0c5a0xXRm5kSHAxCkxtRjZMV1pyWkM1amJHOTFaQzFuWVhKaFoyVXVibVYwTUI0WERUSXhNRFV5TnpFMk1EQXhNMW9YRFRNeE1EVXkKTlRFMk1EQXhNMW93ZERFTk1Bc0dBMVVFQ0F3RVkxQnZaREVOTUFzR0ExVUVCd3dFWTFCdlpERU5NQXNHQTFVRQpDZ3dFWTFCdlpERU5NQXNHQTFVRUN3d0VZMUJ2WkRFMk1EUUdBMVVFQXd3dFkyOXVkSEp2Ykd4bGNpNWpjRzlrCkxXRm5kSHAxTG1GNkxXWnJaQzVqYkc5MVpDMW5ZWEpoWjJVdWJtVjBNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1a1ArUTcvZ2JlVytqa1RuVTVIU09Vcm1FL3haQmdXcjBHWG9MTjZjbXZWVQpYUEFNVnlzTHcrdmJVVXZYRFdLTmcyTHNUd3UrdVVDMDlObnFwalBpWmJNMDVuK2tLdERmS0tyZjFybW5VYkVECitaaERaT243aW9SejArdWxOQ1lGaVlGNUpHZ1JHb1A1dnlOcUZhQTZJWmRiSE1vY21YWnByb1NiTzJ3N1ZkU3EKV1BZdXNTbWxnaExLSi8xVlRuTFc3bzhxYXpxMDFTams4UlJramJaTEdVZ24rbDgrTjdSSnhHMVpvWEJyM1d0dAorWTZ0VVM2TW5tZzRSUTNhWURENGR5dFlFZllabzdPREdoMVhhWTRjalk1RWNKaFNDcFVKMi90Q3E2NU5SOEdTCjkrejBvVGZadW1xVzJrNExBTUhEWWZ5bDlyalpDSmR5dEtiRUNhYXNGUUlEQVFBQm96d3dPakE0QmdOVkhSRUUKTVRBdmdpMWpiMjUwY205c2JHVnlMbU53YjJRdFlXZDBlblV1WVhvdFptdGtMbU5zYjNWa0xXZGhjbUZuWlM1dQpaWFF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUY3V0s3RDNZcnVZdW1MMWZZQVU4K1JvS2FmWEtlYmUraVQ4ClR1N3BwTTJGMTRHcU5hajljNVpOSzNqa3pWREZBa2czajVUZGpvRjVIQWZOUE10WUd1TEdJWXpYdmpTaVpwZlcKcGNHbVdURitKS0VVUGpTVWc1LzlOck1EQjNIWnp5KzY0bWlEWHNnQWRWZDl0bG1MYm5XRlFwQnlEVkVLU01WUQpUVFByZEJ6M1NrTzByZW9wV0dYWTE5VlhXNVgxY1VoOUp1ZkpTWGMraXFMZ0FwRFNtVDJqRTJ6U0Mwc1ZNQmZKCkZQVXNFZ0R0YUlWdXhKR0lITGk3VjlmSmtHNVpPaWswVmJOcnRESnQvK2NjQXFMeExSQXdCK2ExTkNWMk9FQzQKRDIvYkZ1NFJ4VmpheUoyZEV2T21Ic3ZMZGhYNzhaMlBTUXRreVZQWVhvMm1qOWRMb3IwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
AVI_CLOUD_NAME: Default-Cloud
AVI_CONTROLLER: controller.cpod-agtzu.az-fkd.cloud-garage.net
AVI_DATA_NETWORK: Frontend
AVI_DATA_NETWORK_CIDR: 10.30.3.0/24
AVI_ENABLE: "true"
AVI_LABELS: ""
AVI_PASSWORD: <encoded:SDN2TVgxYXNxMU0h>
AVI_SERVICE_ENGINE_GROUP: Default-Group
AVI_USERNAME: admin
CLUSTER_CIDR: 100.96.0.0/11
CLUSTER_NAME: tkgm
CLUSTER_PLAN: dev
ENABLE_CEIP_PARTICIPATION: "false"
ENABLE_MHC: "true"
IDENTITY_MANAGEMENT_TYPE: none
INFRASTRUCTURE_PROVIDER: vsphere
LDAP_BIND_DN: ""
LDAP_BIND_PASSWORD: ""
LDAP_GROUP_SEARCH_BASE_DN: ""
LDAP_GROUP_SEARCH_FILTER: ""
LDAP_GROUP_SEARCH_GROUP_ATTRIBUTE: ""
LDAP_GROUP_SEARCH_NAME_ATTRIBUTE: cn
LDAP_GROUP_SEARCH_USER_ATTRIBUTE: DN
LDAP_HOST: ""
LDAP_ROOT_CA_DATA_B64: ""
LDAP_USER_SEARCH_BASE_DN: ""
LDAP_USER_SEARCH_FILTER: ""
LDAP_USER_SEARCH_NAME_ATTRIBUTE: ""
LDAP_USER_SEARCH_USERNAME: userPrincipalName
OIDC_IDENTITY_PROVIDER_CLIENT_ID: ""
OIDC_IDENTITY_PROVIDER_CLIENT_SECRET: ""
OIDC_IDENTITY_PROVIDER_GROUPS_CLAIM: ""
OIDC_IDENTITY_PROVIDER_ISSUER_URL: ""
OIDC_IDENTITY_PROVIDER_NAME: ""
OIDC_IDENTITY_PROVIDER_SCOPES: ""
OIDC_IDENTITY_PROVIDER_USERNAME_CLAIM: ""
SERVICE_CIDR: 100.64.0.0/13
TKG_HTTP_PROXY: http://172.17.20.1:3128
TKG_HTTP_PROXY_ENABLED: "true"
TKG_HTTPS_PROXY: http://172.17.20.1:3128
TKG_NO_PROXY: 172.17.20.0/24,10.30.0.0/24
VSPHERE_CONTROL_PLANE_DISK_GIB: "20"
VSPHERE_CONTROL_PLANE_ENDPOINT: 172.17.20.121
VSPHERE_CONTROL_PLANE_MEM_MIB: "4096"
VSPHERE_CONTROL_PLANE_NUM_CPUS: "2"
VSPHERE_DATACENTER: /cPod-AGTZU
VSPHERE_DATASTORE: /cPod-AGTZU/datastore/vsanDatastore
VSPHERE_FOLDER: /cPod-AGTZU/vm/TKG
VSPHERE_NETWORK: Management
VSPHERE_PASSWORD: <encoded:SDN2TVgxYXNxMU0h>
VSPHERE_RESOURCE_POOL: /cPod-AGTZU/host/Cluster/Resources/TKG
VSPHERE_SERVER: vcsa.cpod-agtzu.az-fkd.cloud-garage.net
VSPHERE_SSH_AUTHORIZED_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDmsBF8HGkl+gr0KlH6jJGaSLpVbaY8Yrm7nkmj9hR/EM2m6eYYHqg8LNTmQT2DR35dr0PXHiyWaT4BC9qA3qCJYrCpGE4eO9fhB5gYhOpaZ/5YgZNKarhGR7LQva+LRInJPH7KWR/TvQE0dOaQ+QsIWoEEZvAgeOsroFN5JlMtVZCr/VmpRL5kOHI0cdmycYXTgChWCCEqmjVsc+Z+vZSjSl96m5uk1qGOUX/1YdRuVNhR8o2SptO0EHUD0Wns3c3mpqqPtFOrWcFbWJ8CQRktaQfsXzb6Racc+FC1vexfXFaU9yCXMyfs+fzeknrnHiGpW3Dn9sIct1eT4Swva42D grease-monkey@grease-monkey
VSPHERE_TLS_THUMBPRINT: ""
VSPHERE_USERNAME: administrator@cpod-agtzu.az-fkd.cloud-garage.net
VSPHERE_WORKER_DISK_GIB: "20"
VSPHERE_WORKER_MEM_MIB: "4096"
VSPHERE_WORKER_NUM_CPUS: "2"
