kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: primary 
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "${STORAGE_CLASS}"
